import type { FastifyInstance, FastifyRequest, FastifyReply } from 'fastify';
import { z } from 'zod';
import { nexriskApi, snakeToCamel } from '../services/nexrisk-api.js';

// Request schemas
const traderParams = z.object({
  login: z.coerce.number().int().positive(),
});

export async function explanationsRoutes(fastify: FastifyInstance): Promise<void> {
  /**
   * GET /api/explanations/trader/:login
   * Get comprehensive explanation with current state, behavior history, and Claude explanations
   * 
   * This is the main endpoint for the trader detail view.
   * Response includes:
   * - current: Current classification state with template explanation
   * - previousClassifications: History of classifications
   * - claudeExplanations: All Claude-generated explanations (with staleness info)
   * - actions.showExplainButton: Whether to show "Explain" button (LOW/MEDIUM risk)
   */
  fastify.get(
    '/explanations/trader/:login',
    {
      preHandler: [fastify.authenticate, fastify.requireCapability('traders.details')],
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      const { login } = traderParams.parse(request.params);

      const response = await nexriskApi.get(`/api/v1/explanations/trader/${login}`);

      if (!response.ok) {
        return reply.code(response.status).send(response.error);
      }

      const data = snakeToCamel(response.data as Record<string, unknown>);
      return reply.send(data);
    }
  );

  /**
   * POST /api/explanations/trader/:login/generate
   * Generate Claude explanation on-demand ("Explain" button)
   * 
   * This endpoint is called when user clicks "Explain" for LOW/MEDIUM risk traders.
   * For HIGH/CRITICAL, explanations are auto-generated by async workers.
   * 
   * Returns 403 if risk level doesn't allow on-demand generation.
   */
  fastify.post(
    '/explanations/trader/:login/generate',
    {
      preHandler: [fastify.authenticate, fastify.requireCapability('explain.generate')],
    },
    async (request: FastifyRequest, reply: FastifyReply) => {
      const { login } = traderParams.parse(request.params);

      const response = await nexriskApi.post(`/api/v1/explanations/trader/${login}/generate`);

      if (!response.ok) {
        return reply.code(response.status).send(response.error);
      }

      const data = snakeToCamel(response.data as Record<string, unknown>);
      
      // Log successful generation for cost tracking
      fastify.log.info({
        action: 'explanation.generated',
        login,
        provider: (data as Record<string, unknown>).provider,
        costUsd: (data as Record<string, unknown>).costUsd,
      });

      return reply.send(data);
    }
  );

  /**
   * GET /api/explanations/costs
   * Get Claude API cost tracking and usage statistics
   */
  fastify.get(
    '/explanations/costs',
    {
      preHandler: [fastify.authenticate, fastify.requireCapability('llm.status')],
    },
    async (_request: FastifyRequest, reply: FastifyReply) => {
      const response = await nexriskApi.get('/api/v1/explanations/costs');

      if (!response.ok) {
        return reply.code(response.status).send(response.error);
      }

      const data = snakeToCamel(response.data as Record<string, unknown>);
      return reply.send(data);
    }
  );

  /**
   * GET /api/explanations/queue
   * Get async worker queue status for CRITICAL alert processing
   */
  fastify.get(
    '/explanations/queue',
    {
      preHandler: [fastify.authenticate, fastify.requireCapability('llm.status')],
    },
    async (_request: FastifyRequest, reply: FastifyReply) => {
      const response = await nexriskApi.get('/api/v1/explanations/queue');

      if (!response.ok) {
        return reply.code(response.status).send(response.error);
      }

      const data = snakeToCamel(response.data as Record<string, unknown>);
      return reply.send(data);
    }
  );

  /**
   * GET /api/llm/status
   * Get status of all LLM providers
   */
  fastify.get(
    '/llm/status',
    {
      preHandler: [fastify.authenticate, fastify.requireCapability('llm.status')],
    },
    async (_request: FastifyRequest, reply: FastifyReply) => {
      const response = await nexriskApi.get('/api/v1/llm/status');

      if (!response.ok) {
        return reply.code(response.status).send(response.error);
      }

      const data = snakeToCamel(response.data as Record<string, unknown>);
      return reply.send(data);
    }
  );
}
